name: imagtrad
favicon: null
layout_spectrum: 0.31023666937835515
typography_spectrum: 0.4148682840168476
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9382507870905101
  lightness: 0.7198136430233717
  saturation: 0.303632206749171
  rhythmicContrast: 0.45554360072128475
purpose: []
